# Generated by Django 3.0.1 on 2019-12-23 01:17

from django.db import migrations

def create_data(apps, schema_editor):
    Customer = apps.get_model('customers', 'Customer')
    Customer(name="Галимьянов Артём", birthday="1998-04-17", address="пл Шокина",
             doctorCert="Доктор Воловиц", certExpiration="2019-12-30", category="H").save()

def create_data2(apps, schema_editor):
    Couch = apps.get_model('customers', 'Couch')
    Couch(couchID=1, name="Беспалов").save()

def create_data3(apps, schema_editor):
    Schedule = apps.get_model('customers', 'Schedule')
    Schedule(day="2019-12-23", start="10:00:00", end="11:00:00", counter=1,
             duty=1, cust=1, category="H").save()

def create_data4(apps, schema_editor):
    Cost = apps.get_model('customers', 'Cost')
    Cost(costID=1, category="H", money=100).save()
    Cost(costID=2, category="D", money=200).save()
    Cost(costID=3, category="L", money=300).save()
    Cost(costID=4, category="S", money=400).save()
    Cost(costID=5, category="M", money=500).save()
    Cost(costID=6, category="G", money=600).save()

class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
        migrations.RunPython(create_data2),
        migrations.RunPython(create_data4),
        migrations.RunPython(create_data3)
    ]
