# Generated by Django 3.0.1 on 2019-12-23 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('costID', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('H', 'Оздоровительное плавание'), ('D', 'Группы инвалидов'), ('L', 'Обучение плаванию'), ('S', 'Группы спортивного плавания'), ('M', 'Группы от предприятий'), ('G', 'Группы по программам поддержки Правительства')], default=None, max_length=1, null=True)),
                ('money', models.FloatField(verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Стоимость категорий',
                'verbose_name_plural': 'Стоимость категорий',
            },
        ),
        migrations.CreateModel(
            name='Couch',
            fields=[
                ('couchID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Тренера',
                'verbose_name_plural': 'Тренера',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('custID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('address', models.TextField(blank=True, null=True)),
                ('doctorCert', models.CharField(max_length=255, verbose_name='Врач')),
                ('certExpiration', models.DateField(verbose_name='Срок справки')),
                ('category', models.CharField(choices=[('H', 'Оздоровительное плавание'), ('D', 'Группы инвалидов'), ('L', 'Обучение плаванию'), ('S', 'Группы спортивного плавания'), ('M', 'Группы от предприятий'), ('G', 'Группы по программам поддержки Правительства')], default=None, max_length=1, null=True)),
            ],
            options={
                'verbose_name': 'Посетители',
                'verbose_name_plural': 'Посетители',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateField(verbose_name='День')),
                ('start', models.TimeField(verbose_name='Время начала')),
                ('end', models.TimeField(verbose_name='Время конца')),
                ('counter', models.IntegerField(verbose_name='Количество')),
                ('category', models.CharField(choices=[('H', 'Оздоровительное плавание'), ('D', 'Группы инвалидов'), ('L', 'Обучение плаванию'), ('S', 'Группы спортивного плавания'), ('M', 'Группы от предприятий'), ('G', 'Группы по программам поддержки Правительства')], default=None, max_length=1, null=True)),
                ('cust', models.ManyToManyField(null=True, to='customers.Customer')),
                ('duty', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='customers.Couch')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
            },
        ),
    ]
